import crypto from 'crypto';
const COOKIE='nathoeng_account_session';
function decode(v){let b=v.replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';return Buffer.from(b,'base64').toString()}
function sign(v,s){return crypto.createHmac('sha256',s).update(v).digest('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function admin(req){const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='));if(!raw)return null;const t=decodeURIComponent(raw.slice(COOKIE.length+1)),p=t.split('.'),s=process.env.ACCOUNT_BRIDGE_KEY;if(!s||p.length!==2)return null;const e=sign(p[0],s),a=Buffer.from(p[1]),b=Buffer.from(e);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const d=JSON.parse(decode(p[0]));return d.role==='admin'&&d.exp>Date.now()?d:null}catch{return null}}
function cfg(){let url=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;url=String(url||'').trim().replace(/\/+$/,'');if(url&&!/^https?:\/\//i.test(url))url='https://'+url;return{url,key}}
async function db(url,key,path,opt={}){const base=url.includes('/rest/v1')?url:url+'/rest/v1';const target=new URL(path,base.replace(/\/+$/,'')+'/');const r=await fetch(target.toString(),{...opt,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:JSON.stringify(d));return d}
export default async function handler(req,res){const session=admin(req);if(!session)return res.status(403).json({success:false,message:'Admin permission required'});const{url,key}=cfg();if(!url||!key)return res.status(500).json({success:false,message:'Server database key is missing'});const route=String(req.query?.route||'summary');try{
 if(req.method==='GET'&&route==='summary'){const [projects,vendors,bills,funds,categories,attachments]=await Promise.all([db(url,key,'account_projects?select=*&order=created_at.desc'),db(url,key,'account_vendors?select=*&order=name'),db(url,key,'account_bill_balances?select=*&status=neq.void&order=bill_date.desc'),db(url,key,'account_funds?select=*&is_active=eq.true&order=name'),db(url,key,'account_categories?select=*&type=eq.expense&is_active=eq.true&order=sort_order'),db(url,key,'account_bill_attachments?select=*&order=sort_order,uploaded_at')]);const byBill={};for(const a of attachments||[])(byBill[a.bill_id]??=[]).push(a);return res.json({success:true,projects,vendors,bills:(bills||[]).map(b=>({...b,attachments:byBill[b.id]||[]})),funds,categories})}
 if(req.method==='GET'&&route==='bill-print'){const id=String(req.query?.id||'');if(!id)return res.status(400).json({success:false,message:'ไม่พบรหัสบิล'});const [bills,attachments]=await Promise.all([db(url,key,'account_bill_balances?id=eq.'+encodeURIComponent(id)+'&select=*'),db(url,key,'account_bill_attachments?bill_id=eq.'+encodeURIComponent(id)+'&select=*&order=sort_order,uploaded_at')]);if(!bills?.[0])return res.status(404).json({success:false,message:'ไม่พบบิล'});return res.json({success:true,bill:{...bills[0],attachments:attachments||[]}})}
 if(req.method==='POST'&&route==='project'){const x=req.body||{};const d=await db(url,key,'account_projects',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:String(x.name||'').trim(),description:x.description||null,budget:x.budget?Number(x.budget):null,started_at:x.started_at||null})});return res.json({success:true,item:d?.[0]})}
 if(req.method==='POST'&&route==='vendor'){const x=req.body||{};const d=await db(url,key,'account_vendors',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:String(x.name||'').trim(),contact_name:x.contact_name||null,phone:x.phone||null,note:x.note||null})});return res.json({success:true,item:d?.[0]})}
 if(req.method==='POST'&&route==='bill'){const x=req.body||{},amount=Number(x.amount),paid=Number(x.paid_amount||0);if(!(amount>0)||paid<0||paid>amount)return res.status(400).json({success:false,message:'ยอดชำระไม่ถูกต้อง'});const d=await db(url,key,'account_expense_bills',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_date:x.bill_date,project_id:x.project_id||null,vendor_id:x.vendor_id||null,category_id:x.category_id||null,title:x.title,amount,due_date:x.due_date||null,bill_no:x.bill_no||null,description:x.description||null,created_by:String(session.memberId||'admin')})});const bill=d?.[0];if(paid>0&&bill)await db(url,key,'account_expense_payments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_id:bill.id,payment_date:x.bill_date,amount:paid,fund_id:x.fund_id||null,payment_method:x.payment_method||'cash',created_by:String(session.memberId||'admin')})});return res.json({success:true,item:bill})}
 if(req.method==='POST'&&route==='bill-update'){const x=req.body||{},amount=Number(x.amount);if(!x.id||!(amount>0))return res.status(400).json({success:false,message:'ข้อมูลบิลไม่ถูกต้อง'});const current=await db(url,key,'account_bill_balances?id=eq.'+encodeURIComponent(x.id)+'&select=id,paid_amount');const paid=Number(current?.[0]?.paid_amount||0);if(amount<paid)return res.status(400).json({success:false,message:'ยอดบิลใหม่ต้องไม่น้อยกว่ายอดที่ชำระแล้ว '+paid+' บาท'});const d=await db(url,key,'account_expense_bills?id=eq.'+encodeURIComponent(x.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_date:x.bill_date,project_id:x.project_id||null,vendor_id:x.vendor_id||null,category_id:x.category_id||null,title:String(x.title||'').trim(),amount,bill_no:x.bill_no||null,due_date:x.due_date||null,description:x.description||null,updated_at:new Date().toISOString()})});await db(url,key,'account_expense_payments?bill_id=eq.'+encodeURIComponent(x.id)+'&select=id',{method:'GET'});const status=paid===0?'unpaid':paid<amount?'partial':'paid';await db(url,key,'account_expense_bills?id=eq.'+encodeURIComponent(x.id),{method:'PATCH',body:JSON.stringify({status})});return res.json({success:true,item:d?.[0]})}
 if(req.method==='POST'&&route==='attachment'){const x=req.body||{};if(!x.bill_id||typeof x.data!=='string')return res.status(400).json({success:false,message:'ข้อมูลไฟล์แนบไม่ครบ'});const m=/^data:image\/(jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(x.data);if(!m)return res.status(400).json({success:false,message:'รองรับรูป JPEG หรือ WebP เท่านั้น'});const bytes=Buffer.from(m[2],'base64');if(bytes.length<20||bytes.length>2*1024*1024)return res.status(400).json({success:false,message:'รูปต้องมีขนาดไม่เกิน 2 MB'});const endpoint=process.env.MEDIA_UPLOAD_URL,mediaKey=process.env.MEDIA_UPLOAD_KEY;if(endpoint!=='https://media.nathoeng.com/upload.php'||!mediaKey)return res.status(503).json({success:false,message:'กรุณาตั้งค่า MEDIA_UPLOAD_URL และ MEDIA_UPLOAD_KEY ใน Vercel ของ account'});const form=new FormData();form.set('folder','account');form.set('file',new Blob([bytes],{type:'image/'+m[1]}),'bill.'+(m[1]==='jpeg'?'jpg':'webp'));const rr=await fetch(endpoint,{method:'POST',headers:{'X-Upload-Key':mediaKey},body:form,redirect:'error',cache:'no-store'});const md=await rr.json().catch(()=>null);if(!rr.ok||md?.ok!==true)return res.status(503).json({success:false,message:rr.status===401?'MEDIA_UPLOAD_KEY ไม่ตรงกับ media.nathoeng.com':'อัปโหลดหลักฐานไป media.nathoeng.com ไม่สำเร็จ'});if(typeof md.url!=='string'||!/^https:\/\/media\.nathoeng\.com\/uploads\/account\/\d{4}\/\d{2}\/[a-f0-9]{32}\.webp$/.test(md.url))return res.status(503).json({success:false,message:'Media ตอบ URL ไม่ถูกต้อง'});const a=await db(url,key,'account_bill_attachments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_id:x.bill_id,file_type:x.file_type||'receipt',file_url:md.url,original_filename:String(x.name||'bill.jpg').slice(0,200),mime_type:'image/webp',file_size:Number(md.bytes)||bytes.length,uploaded_by:String(session.memberId||'admin')})});return res.json({success:true,item:a?.[0]})}
 if(req.method==='POST'&&route==='payment'){const x=req.body||{};const d=await db(url,key,'account_expense_payments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_id:x.bill_id,payment_date:x.payment_date,amount:Number(x.amount),fund_id:x.fund_id||null,payment_method:x.payment_method||'cash',reference_no:x.reference_no||null,note:x.note||null,prepared_by:String(x.prepared_by||'').trim()||null,checked_by:String(x.checked_by||'').trim()||null,recorded_at:new Date().toISOString(),created_by:String(session.memberId||'admin')})});return res.json({success:true,item:d?.[0]})}
 return res.status(405).json({success:false,message:'Method not allowed'});
}catch(e){console.error(e);return res.status(500).json({success:false,message:e.message})}}