import crypto from 'crypto';
const COOKIE='nathoeng_account_session';
function decode(v){let b=v.replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';return Buffer.from(b,'base64').toString()}
function sign(v,s){return crypto.createHmac('sha256',s).update(v).digest('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function admin(req){const raw=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='));if(!raw)return null;const t=decodeURIComponent(raw.slice(COOKIE.length+1)),p=t.split('.'),s=process.env.ACCOUNT_BRIDGE_KEY;if(!s||p.length!==2)return null;const e=sign(p[0],s),a=Buffer.from(p[1]),b=Buffer.from(e);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const d=JSON.parse(decode(p[0]));return d.role==='admin'&&d.exp>Date.now()?d:null}catch{return null}}
function cfg(){const url=process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;return{url,key}}
async function db(url,key,path,opt={}){const r=await fetch(url+'/rest/v1/'+path,{...opt,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(typeof d==='string'?d:JSON.stringify(d));return d}
export default async function handler(req,res){const session=admin(req);if(!session)return res.status(403).json({success:false,message:'Admin permission required'});const{url,key}=cfg();if(!url||!key)return res.status(500).json({success:false,message:'Server database key is missing'});const route=String(req.query?.route||'summary');try{
 if(req.method==='GET'&&route==='summary'){const [projects,vendors,bills,funds,categories]=await Promise.all([db(url,key,'account_projects?select=*&order=created_at.desc'),db(url,key,'account_vendors?select=*&order=name'),db(url,key,'account_bill_balances?select=*&status=neq.void&order=bill_date.desc'),db(url,key,'account_funds?select=*&is_active=eq.true&order=name'),db(url,key,'account_categories?select=*&type=eq.expense&is_active=eq.true&order=sort_order')]);return res.json({success:true,projects,vendors,bills,funds,categories})}
 if(req.method==='POST'&&route==='project'){const x=req.body||{};const d=await db(url,key,'account_projects',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:String(x.name||'').trim(),description:x.description||null,budget:x.budget?Number(x.budget):null,started_at:x.started_at||null})});return res.json({success:true,item:d?.[0]})}
 if(req.method==='POST'&&route==='vendor'){const x=req.body||{};const d=await db(url,key,'account_vendors',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:String(x.name||'').trim(),contact_name:x.contact_name||null,phone:x.phone||null,note:x.note||null})});return res.json({success:true,item:d?.[0]})}
 if(req.method==='POST'&&route==='bill'){const x=req.body||{},amount=Number(x.amount),paid=Number(x.paid_amount||0);if(!(amount>0)||paid<0||paid>amount)return res.status(400).json({success:false,message:'ยอดชำระไม่ถูกต้อง'});const d=await db(url,key,'account_expense_bills',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_date:x.bill_date,project_id:x.project_id||null,vendor_id:x.vendor_id||null,category_id:x.category_id||null,title:x.title,amount,due_date:x.due_date||null,bill_no:x.bill_no||null,description:x.description||null,created_by:String(session.memberId||'admin')})});const bill=d?.[0];if(paid>0&&bill)await db(url,key,'account_expense_payments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_id:bill.id,payment_date:x.bill_date,amount:paid,fund_id:x.fund_id||null,payment_method:x.payment_method||'cash',created_by:String(session.memberId||'admin')})});return res.json({success:true,item:bill})}
 if(req.method==='POST'&&route==='payment'){const x=req.body||{};const d=await db(url,key,'account_expense_payments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({bill_id:x.bill_id,payment_date:x.payment_date,amount:Number(x.amount),fund_id:x.fund_id||null,payment_method:x.payment_method||'cash',reference_no:x.reference_no||null,note:x.note||null,created_by:String(session.memberId||'admin')})});return res.json({success:true,item:d?.[0]})}
 return res.status(405).json({success:false,message:'Method not allowed'});
}catch(e){console.error(e);return res.status(500).json({success:false,message:e.message})}}